

INSERT INTO ROLE (ID, NAME)
VALUES (1, 'ROLE_STUDENT');

INSERT INTO ROLE (ID, NAME)
VALUES (2, 'ROLE_ADMIN');

INSERT INTO USERS ( FIRST_NAME, LAST_NAME, DOB, ADRESS, PHONE_NUMBER, EMAIL, USERNAME, PASSWORD)
VALUES ( 'Admin','LMS', '1990-08-25' ,'Second Avenue 908', '99887747','admin@admin.com','admin','admin');


INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 2);

